### ISSUE TITLE
 No such property: USER for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by kamal2222ahmed** [Widen/im4java#5]
tried to do a gradle build:
 gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/home/skahmed/im4java/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating root project 'im4java'.
> No such property: USER for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by rnicholus** [comment]
That error is due to a lack of `USER` property, which is used by [the `uploadArchives` task](https://github.com/Widen/im4java/blob/master/build.gradle#L10). Normally, you would specify these in a [gradle.properties file](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties). But this particular gradle task is specific to Widen's internal environment. As you can see, it references a private maven registry where we may want to upload an updated version of this library.

You can just remove this task locally after cloning or forking the project. All other supported gradle tasks should work at that point.
